/**
 * @file `cfcli completion` — auto-generate shell completion scripts from the registry.
 *
 * Supported shells: bash, zsh, fish, powershell
 *
 * The completion script is generated by reading the command registry,
 * so it AUTOMATICALLY includes new commands added in the future.
 *
 * Usage:
 *   cfcli completion bash > /etc/bash_completion.d/cfcli
 *   cfcli completion zsh > ~/.zsh/completions/_cfcli
 *   cfcli completion fish > ~/.config/fish/completions/cfcli.fish
 *   cfcli completion powershell | Out-File -Encoding utf8 cfcli.ps1
 */

const { buildRegistry, flattenCommands } = require('../utils/registry');
const { formatError } = require('../utils/formatter');

function generateBash(registry) {
  const flat = flattenCommands(registry);
  const commands = flat.map(c => c.path.split(' ')[0]);
  const uniqueTop = [...new Set(commands)];

  // Build subcommand completions
  const subMaps = {};
  flat.forEach(c => {
    const parts = c.path.split(' ');
    if (parts.length > 1) {
      const top = parts[0];
      if (!subMaps[top]) subMaps[top] = [];
      subMaps[top].push(parts[1]);
    }
  });

  let script = `# cfcli bash completion — auto-generated
_cfcli() {
  local cur prev opts
  COMPREPLY=()
  cur="${"\\${COMP_WORDS[COMP_CWORD]}"}"
  prev="${"\\${COMP_WORDS[COMP_CWORD-1]}"}"

  # Top-level commands
  if [ $COMP_CWORD -eq 1 ]; then
    opts="${uniqueTop.join(' ')}"
    COMPREPLY=( $(compgen -W "${"\\$opts"}" -- ${"\\$cur"}) )
    return 0
  fi

  # Subcommands
  local cmd=${"\\${COMP_WORDS[1]}"}
  case "$cmd" in
`;

  Object.entries(subMaps).forEach(([top, subs]) => {
    const uniqueSubs = [...new Set(subs)];
    script += `    ${top})\n`;
    script += `      if [ $COMP_CWORD -eq 2 ]; then\n`;
    script += `        opts="${uniqueSubs.join(' ')}"\n`;
    script += `        COMPREPLY=( $(compgen -W "${"\\$opts"}" -- ${"\\$cur"}) )\n`;
    script += `        return 0\n`;
    script += `      fi\n`;
    script += `      ;;\n`;
  });

  script += `  esac\n\n`;
  // Option completion
  script += `  # Complete options\n`;
  script += `  if [[ ${"\\$cur"} == --* ]]; then\n`;
  script += `    opts="--help --json --verbose --all --zone-id --type --name --page --per-page"\n`;
  script += `    COMPREPLY=( $(compgen -W "${"\\$opts"}" -- ${"\\$cur"}) )\n`;
  script += `    return 0\n`;
  script += `  fi\n`;
  script += `}\n`;
  script += `complete -F _cfcli cfcli\n`;

  return script;
}

function generateZsh(registry) {
  const flat = flattenCommands(registry);
  const commands = flat.map(c => c.path.split(' ')[0]);
  const uniqueTop = [...new Set(commands)];

  const subMaps = {};
  flat.forEach(c => {
    const parts = c.path.split(' ');
    if (parts.length > 1) {
      const top = parts[0];
      if (!subMaps[top]) subMaps[top] = [];
      subMaps[top].push(parts[1]);
    }
  });

  let script = `#compdef cfcli\n# cfcli zsh completion — auto-generated\n\n`;
  script += `_cfcli() {\n`;
  script += `  local -a commands\n`;
  script += `  commands=(${uniqueTop.map(c => `'${c}'`).join(' ')})\n\n`;

  script += `  if (( CURRENT == 2 )); then\n`;
  script += `    _values 'command' ${"\\${commands[@]}"}\n`;
  script += `    return\n`;
  script += `  fi\n\n`;

  Object.entries(subMaps).forEach(([top, subs]) => {
    const uniqueSubs = [...new Set(subs)];
    script += `  if [[ ${"\\$words[2]"} == '${top}' ]]; then\n`;
    script += `    if (( CURRENT == 3 )); then\n`;
    script += `      _values 'subcommand' ${uniqueSubs.map(s => `'${s}'`).join(' ')}\n`;
    script += `      return\n`;
    script += `    fi\n`;
    script += `  fi\n`;
  });

  script += `  _arguments --help --json --verbose --all\n`;
  script += `}\n\n`;
  script += `compdef _cfcli cfcli\n`;

  return script;
}

function generateFish(registry) {
  const flat = flattenCommands(registry);
  let script = `# cfcli fish completion — auto-generated\n\n`;

  flat.forEach(c => {
    const parts = c.path.split(' ');
    script += `complete -c cfcli -f -n '__fish_use_subcommand' -a '${parts[0]}' -d '${c.description.replace(/'/g, "\\'")}'\n`;
    if (parts.length > 1) {
      script += `complete -c cfcli -f -n '__fish_seen_subcommand_from ${parts[0]}' -a '${parts[1]}' -d '${c.description.replace(/'/g, "\\'")}'\n`;
    }
    // Options
    (c.options || []).forEach(opt => {
      const longFlag = opt.flags.match(/--[\w-]+/);
      if (longFlag) {
        script += `complete -c cfcli -f -n '__fish_seen_subcommand_from ${parts[0]}' -l '${longFlag[0].replace('--', '')}' -d '${opt.description.replace(/'/g, "\\'")}'\n`;
      }
    });
  });

  return script;
}

function generatePowerShell(registry) {
  const flat = flattenCommands(registry);
  const commands = flat.map(c => c.path.split(' ')[0]);
  const uniqueTop = [...new Set(commands)];

  const subMaps = {};
  flat.forEach(c => {
    const parts = c.path.split(' ');
    if (parts.length > 1) {
      const top = parts[0];
      if (!subMaps[top]) subMaps[top] = [];
      subMaps[top].push(parts[1]);
    }
  });

  let script = `# cfcli PowerShell completion — auto-generated\n`;
  script += `Register-ArgumentCompleter -Native -CommandName cfcli -ScriptBlock {\n`;
  script += `    param($wordToComplete, $commandAst, $cursorPosition)\n\n`;
  script += `    $commandElements = $commandAst.CommandElements\n`;
  script += `    $command = @($commandElements)[0].Value\n`;
  script += `    $previous = if ($commandElements.Count -gt 1) { @($commandElements)[-2].Value } else { '' }\n\n`;
  script += `    $topCommands = @(${uniqueTop.map(c => `'${c}'`).join(', ')})\n\n`;

  script += `    if (-not $wordToComplete) { return }\n\n`;

  script += `    # Top-level completion\n`;
  script += `    if ($commandElements.Count -le 2) {\n`;
  script += `        $topCommands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {\n`;
  script += `            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n`;
  script += `        }\n`;
  script += `        return\n`;
  script += `    }\n\n`;

  Object.entries(subMaps).forEach(([top, subs]) => {
    const uniqueSubs = [...new Set(subs)];
    script += `    if ($previous -eq '${top}') {\n`;
    script += `        @(${uniqueSubs.map(s => `'${s}'`).join(', ')}) | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {\n`;
    script += `            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n`;
    script += `        }\n`;
    script += `        return\n`;
    script += `    }\n`;
  });

  script += `}\n`;

  return script;
}

function completionModule(program) {
  const cmd = program.command('completion').description('Generate shell completion scripts from the command registry');

  cmd
    .command('bash')
    .description('Generate bash completion script')
    .action(() => {
      const registry = buildRegistry(program);
      console.log(generateBash(registry));
    });

  cmd
    .command('zsh')
    .description('Generate zsh completion script')
    .action(() => {
      const registry = buildRegistry(program);
      console.log(generateZsh(registry));
    });

  cmd
    .command('fish')
    .description('Generate fish completion script')
    .action(() => {
      const registry = buildRegistry(program);
      console.log(generateFish(registry));
    });

  cmd
    .command('powershell')
    .description('Generate PowerShell completion script')
    .action(() => {
      const registry = buildRegistry(program);
      console.log(generatePowerShell(registry));
    });
}

module.exports = completionModule;
