/**
 * @file Unit tests for the command registry (P3 core).
 *
 * Verifies that:
 * 1. The registry auto-discovers all commands from a Commander program tree.
 * 2. Options are correctly extracted (flags, description, defaults).
 * 3. Subcommands are recursively walked.
 * 4. flattenCommands produces a correct leaf list.
 * 5. countCommands counts correctly.
 * 6. renderTable produces readable output.
 */

const { Command } = require('commander');
const { buildRegistry, flattenCommands, countCommands, renderTable } = require('../../src/utils/registry');

// Build a mock program tree mimicking the real cfcli structure
function buildMockProgram() {
  const program = new Command();
  program
    .name('cfcli')
    .description('Mock CLI for testing')
    .version('9.9.9')
    .option('-v, --verbose', 'Verbose output')
    .option('-j, --json', 'JSON output');

  // dns command with subcommands
  const dns = program.command('dns').description('Manage DNS Records');
  dns
    .command('list')
    .description('List DNS records')
    .option('-z, --zone-id <zoneId>', 'Zone ID')
    .option('-t, --type <type>', 'Record type')
    .option('--all', 'Fetch all pages')
    .option('--page <N>', 'Page number', '1')
    .action(() => {});

  dns
    .command('add')
    .description('Add a DNS record')
    .option('-t, --type <type>', 'Record type (required)')
    .option('-n, --name <name>', 'Record name')
    .action(() => {});

  // zone command (flat, no subcommands)
  program
    .command('verify')
    .description('Verify API token')
    .action(() => {});

  // r2 with nested subcommands (2 levels deep)
  const r2 = program.command('r2').description('Manage R2 Storage');
  const r2buckets = r2.command('buckets').description('Bucket management');
  r2buckets
    .command('list')
    .description('List buckets')
    .option('--all', 'Fetch all')
    .action(() => {});

  return program;
}

describe('Command Registry', () => {
  let registry;

  beforeAll(() => {
    registry = buildRegistry(buildMockProgram());
  });

  describe('buildRegistry', () => {
    it('extracts version and name from program', () => {
      expect(registry.version).toBe('9.9.9');
      expect(registry.name).toBe('cfcli');
      expect(registry.description).toBe('Mock CLI for testing');
    });

    it('captures global options', () => {
      // Commander auto-adds -h, --help; our options + help = 3
      const flags = registry.globalOptions.map(o => o.flags);
      expect(flags).toContain('-v, --verbose');
      expect(flags).toContain('-j, --json');
    });

    it('discovers top-level commands', () => {
      const names = registry.commands.map(c => c.name);
      expect(names).toContain('dns');
      expect(names).toContain('verify');
      expect(names).toContain('r2');
      // help is auto-generated by Commander; our filter should skip it
      expect(names).not.toContain('help');
    });

    it('recursively walks subcommands', () => {
      const dns = registry.commands.find(c => c.name === 'dns');
      expect(dns.subcommands).toHaveLength(2);
      const subNames = dns.subcommands.map(s => s.name);
      expect(subNames).toEqual(['list', 'add']);
    });

    it('extracts options from subcommands', () => {
      const dns = registry.commands.find(c => c.name === 'dns');
      const list = dns.subcommands.find(s => s.name === 'list');
      expect(list.options).toHaveLength(4);
      const zoneOpt = list.options.find(o => o.flags.includes('--zone-id'));
      expect(zoneOpt).toBeDefined();
      expect(zoneOpt.description).toBe('Zone ID');
    });

    it('extracts default values', () => {
      const dns = registry.commands.find(c => c.name === 'dns');
      const list = dns.subcommands.find(s => s.name === 'list');
      const pageOpt = list.options.find(o => o.flags.includes('--page'));
      expect(pageOpt.defaultValue).toBe('1');
    });

    it('walks 2+ levels deep (r2 > buckets > list)', () => {
      const r2 = registry.commands.find(c => c.name === 'r2');
      expect(r2.subcommands).toHaveLength(1);
      const buckets = r2.subcommands[0];
      expect(buckets.name).toBe('buckets');
      expect(buckets.subcommands).toHaveLength(1);
      expect(buckets.subcommands[0].name).toBe('list');
    });

    it('sets correct path for nested commands', () => {
      const r2 = registry.commands.find(c => c.name === 'r2');
      const buckets = r2.subcommands[0];
      const list = buckets.subcommands[0];
      expect(list.path).toBe('r2 buckets list');
    });
  });

  describe('flattenCommands', () => {
    it('produces a flat list of leaf commands', () => {
      const flat = flattenCommands(registry);
      const paths = flat.map(c => c.path);
      expect(paths).toContain('dns list');
      expect(paths).toContain('dns add');
      expect(paths).toContain('verify');
      expect(paths).toContain('r2 buckets list');
    });

    it('does not include parent commands that have subcommands', () => {
      const flat = flattenCommands(registry);
      const paths = flat.map(c => c.path);
      // dns has subcommands so it should NOT be in the flat list
      expect(paths).not.toContain('dns');
      expect(paths).not.toContain('r2');
      expect(paths).not.toContain('r2 buckets');
    });
  });

  describe('countCommands', () => {
    it('counts all commands including subcommands', () => {
      // dns, dns list, dns add, verify, r2, r2 buckets, r2 buckets list = 7
      expect(countCommands(registry)).toBe(7);
    });
  });

  describe('renderTable', () => {
    it('produces human-readable table', () => {
      const table = renderTable(registry);
      expect(table).toContain('cfcli v9.9.9');
      expect(table).toContain('7 commands');
      expect(table).toContain('dns list');
      expect(table).toContain('dns add');
      expect(table).toContain('r2 buckets list');
      expect(table).toContain('verify');
    });
  });
});
